################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
platform-1224-launchpad/source/adc.obj: ../platform-1224-launchpad/source/adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/adc.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/can.obj: ../platform-1224-launchpad/source/can.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/can.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/crc.obj: ../platform-1224-launchpad/source/crc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/crc.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/dabort.obj: ../platform-1224-launchpad/source/dabort.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/dabort.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/dcc.obj: ../platform-1224-launchpad/source/dcc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/dcc.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/ecap.obj: ../platform-1224-launchpad/source/ecap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/ecap.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/eqep.obj: ../platform-1224-launchpad/source/eqep.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/eqep.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/esm.obj: ../platform-1224-launchpad/source/esm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/esm.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/etpwm.obj: ../platform-1224-launchpad/source/etpwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/etpwm.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/gio.obj: ../platform-1224-launchpad/source/gio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/gio.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/het.obj: ../platform-1224-launchpad/source/het.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/het.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/i2c.obj: ../platform-1224-launchpad/source/i2c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/i2c.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/lin.obj: ../platform-1224-launchpad/source/lin.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/lin.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/mibspi.obj: ../platform-1224-launchpad/source/mibspi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/mibspi.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/notification.obj: ../platform-1224-launchpad/source/notification.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/notification.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_croutine.obj: ../platform-1224-launchpad/source/os_croutine.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_croutine.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_event_groups.obj: ../platform-1224-launchpad/source/os_event_groups.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_event_groups.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_heap.obj: ../platform-1224-launchpad/source/os_heap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_heap.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_list.obj: ../platform-1224-launchpad/source/os_list.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_list.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_mpu_wrappers.obj: ../platform-1224-launchpad/source/os_mpu_wrappers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_mpu_wrappers.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_port.obj: ../platform-1224-launchpad/source/os_port.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_port.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_portasm.obj: ../platform-1224-launchpad/source/os_portasm.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_portasm.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_queue.obj: ../platform-1224-launchpad/source/os_queue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_queue.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_tasks.obj: ../platform-1224-launchpad/source/os_tasks.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_tasks.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/os_timer.obj: ../platform-1224-launchpad/source/os_timer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/os_timer.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/pinmux.obj: ../platform-1224-launchpad/source/pinmux.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/pinmux.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sci.obj: ../platform-1224-launchpad/source/sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sci.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/spi.obj: ../platform-1224-launchpad/source/spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/spi.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_core.obj: ../platform-1224-launchpad/source/sys_core.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_core.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_dma.obj: ../platform-1224-launchpad/source/sys_dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_dma.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_intvecs.obj: ../platform-1224-launchpad/source/sys_intvecs.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_intvecs.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_main.obj: ../platform-1224-launchpad/source/sys_main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_main.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_mpu.obj: ../platform-1224-launchpad/source/sys_mpu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_mpu.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_pcr.obj: ../platform-1224-launchpad/source/sys_pcr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_pcr.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_phantom.obj: ../platform-1224-launchpad/source/sys_phantom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_phantom.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_pmm.obj: ../platform-1224-launchpad/source/sys_pmm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_pmm.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_pmu.obj: ../platform-1224-launchpad/source/sys_pmu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_pmu.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_selftest.obj: ../platform-1224-launchpad/source/sys_selftest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_selftest.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_startup.obj: ../platform-1224-launchpad/source/sys_startup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_startup.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/sys_vim.obj: ../platform-1224-launchpad/source/sys_vim.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/sys_vim.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

platform-1224-launchpad/source/system.obj: ../platform-1224-launchpad/source/system.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/include" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardware-drivers" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/third-party" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/platform-1224-launchpad/source" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/featuredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/hardwaredefs" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/system" --include_path="C:/Users/aless/Documents/UBC Orbit/ADCS_Firm/adcs_firmware/adcs/interfaces" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.6.LTS/include" -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="platform-1224-launchpad/source/system.d_raw" --obj_directory="platform-1224-launchpad/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


